/*
 * Copyright 2011 Matthias van der Vlies
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package core;

import java.io.ByteArrayInputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;

import models.Application;
import models.ApplicationProperty;
import play.Logger;

public class ConfigurationManager {

	private static final String PROPERTY_FILE_COMMENT = "Generated by Play! Application Server";

	private static String getConfigurationFilePath(final Application application) {
		return "apps/" + application.pid + "/conf/application.conf";
	}
	
	private static String getLoggingConfigurationFilePath(final Application application) {
		return "apps/" + application.pid + "/conf/log4j.properties";
	}

	public static void generateConfigurationFiles(final Application application) throws IOException {
		Logger.info("Creating configuration file for application %s", application.pid);
		final Properties properties = new OrderedProperties();
		final Properties logProperties = new OrderedProperties();
		final List<ApplicationProperty> applicationProperties = ApplicationProperty.find("application = ? order by priority", application).fetch();
		for(final ApplicationProperty property : applicationProperties) {
			if(property.key.startsWith("log4j")) {
				logProperties.setProperty(property.key, property.value);
			}
			else {
				properties.setProperty(property.key, property.value);
			}
		}
		final FileOutputStream outputStream = new FileOutputStream(getConfigurationFilePath(application));
		final FileOutputStream logOutputStream = new FileOutputStream(getLoggingConfigurationFilePath(application));
		properties.store(outputStream, PROPERTY_FILE_COMMENT);
		logProperties.store(logOutputStream, PROPERTY_FILE_COMMENT);
		outputStream.close();
		logOutputStream.close();
	}
	
	/**
	 * Read the current configuration from a string and load it into the database
	 * @param application
	 */
	public static void readCurrentConfigurationFromString(final Application application, final String configuration) throws Exception {
		final OrderedProperties properties = new OrderedProperties();
		final InputStream inputStream = new ByteArrayInputStream(configuration.getBytes("ISO-8859-1"));
        properties.load(inputStream);    
        saveProperties(application, properties);
	}
	
	/**
	 * Read the current configuration and load it into the database
	 * @param application
	 */
	public static void readCurrentConfigurationFromFile(final Application application) throws Exception {
		final OrderedProperties properties = new OrderedProperties();
        final FileInputStream inputStream = new FileInputStream(getConfigurationFilePath(application));
        properties.load(inputStream);    
        saveProperties(application, properties);
        
        // we will already add the logging and mode configuration here!
        new ApplicationProperty(application, 1, "application.mode", application.mode.toString()).save();
        
        // logging:
        new ApplicationProperty(application, 2, "log4j.rootLogger", "ERROR, Rolling").save();
        new ApplicationProperty(application, 3, "log4j.logger.play", "INFO").save();
        new ApplicationProperty(application, 4, "log4j.appender.Rolling", "org.apache.log4j.RollingFileAppender").save();
        new ApplicationProperty(application, 5, "log4j.appender.Rolling.File", "logs/" + application.pid + ".log").save();
        new ApplicationProperty(application, 6, "log4j.appender.Rolling.MaxFileSize", "1MB").save();
        new ApplicationProperty(application, 7, "log4j.appender.Rolling.MaxBackupIndex", "100").save();
        new ApplicationProperty(application, 8, "log4j.appender.Rolling.layout", "org.apache.log4j.PatternLayout").save();
        new ApplicationProperty(application, 9, "log4j.appender.Rolling.layout.ConversionPattern", "%d{ABSOLUTE} %-5p ~ %m%n").save();
	}
	
	public static void saveProperties(final Application application, final OrderedProperties properties) {
		Logger.info("config(%s): Reading application.conf", application.pid);
		
		// cache existing properties
		final Map<String, ApplicationProperty> existingProperties = new HashMap<String, ApplicationProperty>();
		for(final ApplicationProperty property : application.properties) {
			existingProperties.put(property.key, property);
		}
		
		int priority = 100;
		for(final Object rawKey : properties.keySet()) {
			final String key = (String) rawKey;
			final String value = (String) properties.getProperty(key);
			
			if("application.mode".equals(key) || key.startsWith("log4j")) {
				// ignore since the AS is responsible for generating this
				continue;
			}
			
			ApplicationProperty property = existingProperties.get(key);
			
			if(property == null) {
				// new property
				property = new ApplicationProperty();
				property.application = application;
				property.key = key;
				property.value = value;
				property.priority = priority;
			}
			else {
				existingProperties.remove(key);
				
				// update priority
				property.priority = priority;
			}
			
			Logger.info("config(%s): %s = %s", application.pid, key, value);
			
			property.save();
			priority++;
		}
		
		// remove deleted properties
		if(existingProperties.size() > 0) {
			for(final ApplicationProperty property : existingProperties.values()) {
				property.delete();
				Logger.info("config(%s): deleted %s", application.pid, property.key);
			}
		}
	}
}
